version: "3"

services:

  web:
    image: nginx:alpine
    container_name: bshp_nginx
    ports:
      - 8063:80
    depends_on:
      - app
    volumes:
      - ./.nginx/conf.d:/etc/nginx/conf.d
    networks:
      - custom
  app:
    container_name: bshp_final
    image: nickgott/bshp_final:latest
    environment:
      - DB_HOST=db
      - DB_PORT=27017
      - USE_AUTHENTICATION=False
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - "8061:8061"
    volumes:
      - ./app_settings:/app_settings
    networks:
      - custom
    depends_on:
      - db
  db:

    image: mongo
    container_name: bshp_db
    ports:
      - "27018:27017"
    volumes:
      - ./db/data:/data/db
    networks:
      - custom

networks:
  custom:
    driver: bridge